name: Install VS Code Extensions (Demo)

on:
  workflow_dispatch:   # nur manuell startbar im GitHub UI

jobs:
  install-only:
    name: "⬇️ Nur Install-Skript testen"
    runs-on: windows-latest

    steps:
      - name: 📥 Repository auschecken
        uses: actions/checkout@v4

      - name: ⚙️ Stelle VS Code CLI bereit
        run: |
          echo "C:\Users\runneradmin\AppData\Local\Programs\Microsoft VS Code\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          code --version

      - name: ▶️ Führe Install-Skript aus
        shell: pwsh
        run: |
          ./scripts/Install-Extensions.ps1 -LogFile "$env:TEMP\InstallOnly.log"

      - name: 📦 Lade Log als Artefakt hoch
        uses: actions/upload-artifact@v4
        with:
          name: install-only-log
          path: ${{ runner.temp }}
