name: Install VS Code Extensions (Demo)

on:
  workflow_dispatch:

jobs:
  install-only:
    name: "⬇️ Nur Install-Skript testen"
    runs-on: windows-latest

    steps:
      - name: 📥 Repository auschecken
        uses: actions/checkout@v4

      - name: ⚙️ Stelle VS Code CLI bereit
        shell: pwsh
        run: |
          $paths = @(
            "C:\Users\runneradmin\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd",
            "C:\Program Files\Microsoft VS Code\bin\code.cmd"
          )

          $cliPath = $null
          foreach ($p in $paths) {
            if (Test-Path $p) {
              $cliPath = $p
              break
            }
          }

          if (-not $cliPath) {
            if ($env:GITHUB_ACTIONS -eq "true") {
              Write-Host "⚠️ VS Code CLI nicht gefunden – lade offiziellen Installer..."
              Invoke-WebRequest -Uri "https://update.code.visualstudio.com/latest/win32-x64-user/stable" -OutFile vscode_installer.exe
              Start-Process -FilePath .\vscode_installer.exe -ArgumentList "/VERYSILENT /MERGETASKS=!runcode" -Wait
              $cliPath = "C:\Users\runneradmin\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd"
            }
            else {
              Write-Host "⚠️ VS Code CLI nicht gefunden – versuche Winget..."
              winget install -e --id Microsoft.VisualStudioCode -h
              $cliPath = "C:\Program Files\Microsoft VS Code\bin\code.cmd"
            }
          }

          Write-Host "✅ Verwende VS Code CLI: $cliPath"
          echo (Split-Path $cliPath) | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          & $cliPath --version

      - name: ▶️ Führe Install-Skript aus
        shell: pwsh
        run: ./scripts/Install-Extensions.ps1 -LogFile "$env:TEMP\InstallOnly.log"

      - name: 📦 Lade Log als Artefakt hoch
        uses: actions/upload-artifact@v4
        with:
          name: install-only-log
          path: ${{ runner.temp }}
