name: Install VS Code Extensions (Demo)

on:
  workflow_dispatch:

jobs:
  install-only:
    name: "⬇️ Nur Install-Skript testen"
    runs-on: windows-latest

    steps:
      - name: 📥 Repository auschecken
        uses: actions/checkout@v4

      - name: ⚙️ Stelle VS Code CLI bereit
        shell: pwsh
        run: |
          $possiblePaths = @(
            "C:\Users\runneradmin\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd",
            "C:\Program Files\Microsoft VS Code\bin\code.cmd"
          )

          $found = $false
          foreach ($p in $possiblePaths) {
            if (Test-Path $p) {
              Write-Host "✅ VS Code CLI gefunden: $p"
              echo (Split-Path $p) | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
              $found = $true
              break
            }
          }

          if (-not $found) {
            Write-Host "⚠️ VS Code CLI nicht gefunden, installiere mit winget..."
            winget install -e --id Microsoft.VisualStudioCode -h
            echo "C:\Program Files\Microsoft VS Code\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          }

          code --version

      - name: ▶️ Führe Install-Skript aus
        shell: pwsh
        run: ./scripts/Install-Extensions.ps1 -LogFile "$env:TEMP\InstallOnly.log"

      - name: 📦 Lade Log als Artefakt hoch
        uses: actions/upload-artifact@v4
        with:
          name: install-only-log
          path: ${{ runner.temp }}
